# Generated by Django 2.0.5 on 2018-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('qq', models.CharField(blank=True, max_length=20)),
                ('weixin', models.CharField(blank=True, max_length=50)),
                ('openid', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.BooleanField(default=0)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
